- label: "Pull request pipeline"
  agents:
    provider: gcp
    imageProject: elastic-images-prod
    image: family/platform-ingest-logstash-ubuntu-2204
    machineType: "n2-standard-4"
    diskSizeGb: 64
  command: |
    #!/usr/bin/env bash
    set -eo pipefail
    echo "--- Pull request pipeline starting..."
