# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('org.apache.kafka', 'kafka-clients', '2.4.1')
require_jar('com.github.luben', 'zstd-jni', '1.4.3-1')
require_jar('org.slf4j', 'slf4j-api', '1.7.28')
require_jar('org.lz4', 'lz4-java', '1.6.0')
require_jar('org.xerial.snappy', 'snappy-java', '1.1.7.3')
