# AUTOGENERATED BY THE GRADLE SCRIPT. DO NOT EDIT.

require 'jar_dependencies'
require_jar('io.confluent', 'kafka-avro-serializer', '5.5.1')
require_jar('io.confluent', 'kafka-schema-serializer', '5.5.1')
require_jar('io.confluent', 'common-config', '5.5.1')
require_jar('org.apache.avro', 'avro', '1.9.2')
require_jar('io.confluent', 'kafka-schema-registry-client', '5.5.1')
require_jar('org.apache.kafka', 'kafka_2.12', '2.5.1')
require_jar('io.confluent', 'common-utils', '5.5.1')
require_jar('javax.ws.rs', 'javax.ws.rs-api', '2.1.1')
require_jar('org.glassfish.jersey.core', 'jersey-common', '2.33')
require_jar('org.apache.kafka', 'kafka-clients', '2.5.1')
require_jar('com.github.luben', 'zstd-jni', '1.4.4-7')
require_jar('org.slf4j', 'slf4j-api', '1.7.30')
require_jar('org.lz4', 'lz4-java', '1.7.1')
require_jar('org.xerial.snappy', 'snappy-java', '1.1.7.3')
